version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production

  api:
    image: node:18-alpine
    command: npx json-server --watch db.json --host 0.0.0.0 --port 3000
    volumes:
      - ./db.json:/app/db.json
    ports:
      - "3000:3000"
    working_dir: /app