[build]
  command = "ng build --configuration=production"
  publish = "dist/your-project-name"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
